user:
    password:
        hashed: ENC[AES256_GCM,data:7P9vC5bZcI3wsHbAcTdD48aoz8FiRhhf6NnzUxSLb40WW/wrzb4yNpU00ZEx5MgyUvykWh19dOzM8UTvBJPzaq4ZwgbIUFlPFw==,iv:zFHTtsR5AozIjOG3GAi98ZUQ0htsmKFwKER2FJ+g5Gs=,tag:ZrC3uYTmu+W/fTn7hGP4vQ==,type:str]
nix-cache:
    private_key: ENC[AES256_GCM,data:gMu8qC9dmgdxt2J32qSeAo2/Iud1UFLUeBrut08YXM4rovN2D7RB1CGSwqQ+44iyNIBZKb83LkQvLxwdlUAgYkXK8/XFY6VazgJ3P+O3mtOEW9yQZqlNMjfprDTavsJ+SrhwNMiPsA==,iv:IrmkVDtDA/BwLwP8ioDVhKws4w62GOmd6PgmAax6zbA=,tag:bGFEDQ3DllW9/dQR02laAA==,type:str]
    public_key: ENC[AES256_GCM,data:29B1pwKU+dQB08ONnOhWsaaBwAYIO/DLZ7ZGdXwPlULupxnlY4/Hbm5bWLJwZzvgWqbnSjiQxjjAU34=,iv:OinB87rfHetEN8xHbqttAYqIsSyE5MVG86pZupSBiug=,tag:TBkrp18C232+PBvILFDCpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSnlvNWl2Z1d6Y2xSMVEy
            dVdFRi84bFJXTHRlM08raUw4NXB5S283V2dNCjR4TEZESW5mOWwzOEZsKzd2cUZk
            b2pjUnkyWWJiTlRSeUZPL0ZTcHhhUEUKLS0tIHhBRys1cTRjZnZxS0J5T2taL2tU
            eU1hdEVWTWY5YktHTlNXczRoUzloUkEKKfpMzR1zJqpqqxUGYW9X8Nn8DRAqI9zC
            aGDTfTNKeOqPdYkqHs+bUpclrUE68kkgfzQA5vQay6tnF5tSj1h2UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p0el9phnfxnjnaa9mgqtru4ke30vcae7vlzffmre2czf4r5w54rqwm8f0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaEVCdC9uUmxaYVp5dU9K
            anQ1RitaVG9PSkRZVFFaSWNSV01XZmFhSm1JCnE0TTVRWUkwTVZaUmxmT3lrdDhJ
            aTZQclcrUU94UUZOZ0ZCeVFTZ1QvR0EKLS0tIFhSbjVXYVVINGkxL25tb2xVd0RN
            dDNpSlFrMWIxM2NZZUFybGFiQ2hELzQKDQEViMt7sEcjebOqNK1+jfSe7SDxofXT
            jV6Lflxh6vVZyZbIQDHc5+tdXEW+QzJejtoZX8Rgky1PQl9lPfcFnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T00:41:12Z"
    mac: ENC[AES256_GCM,data:U88sHThG2s6EuAOHofy2pC8baIKyMQyOJikAmKYcXYJmabOtkR4MpshqCMwsoQ53478HKeHEZOYkZtbrYUwgIfiEov7zoibYMe8dDQ69uDrx6gumnv6iPB9C33mXlR7GpFwBtGrJOByT/bpafMpz1GsVGBB6Lz2/82NbBzvwX38=,iv:7Tvpc0chLvVVGIWXBm/Dyx4Sv7G/rKCdKxRGPbxE7dw=,tag:KQX2I7WChKF7OIX3RS1S5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
