user:
    password:
        hashed: ENC[AES256_GCM,data:7P9vC5bZcI3wsHbAcTdD48aoz8FiRhhf6NnzUxSLb40WW/wrzb4yNpU00ZEx5MgyUvykWh19dOzM8UTvBJPzaq4ZwgbIUFlPFw==,iv:zFHTtsR5AozIjOG3GAi98ZUQ0htsmKFwKER2FJ+g5Gs=,tag:ZrC3uYTmu+W/fTn7hGP4vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSnlvNWl2Z1d6Y2xSMVEy
            dVdFRi84bFJXTHRlM08raUw4NXB5S283V2dNCjR4TEZESW5mOWwzOEZsKzd2cUZk
            b2pjUnkyWWJiTlRSeUZPL0ZTcHhhUEUKLS0tIHhBRys1cTRjZnZxS0J5T2taL2tU
            eU1hdEVWTWY5YktHTlNXczRoUzloUkEKKfpMzR1zJqpqqxUGYW9X8Nn8DRAqI9zC
            aGDTfTNKeOqPdYkqHs+bUpclrUE68kkgfzQA5vQay6tnF5tSj1h2UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p0el9phnfxnjnaa9mgqtru4ke30vcae7vlzffmre2czf4r5w54rqwm8f0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaEVCdC9uUmxaYVp5dU9K
            anQ1RitaVG9PSkRZVFFaSWNSV01XZmFhSm1JCnE0TTVRWUkwTVZaUmxmT3lrdDhJ
            aTZQclcrUU94UUZOZ0ZCeVFTZ1QvR0EKLS0tIFhSbjVXYVVINGkxL25tb2xVd0RN
            dDNpSlFrMWIxM2NZZUFybGFiQ2hELzQKDQEViMt7sEcjebOqNK1+jfSe7SDxofXT
            jV6Lflxh6vVZyZbIQDHc5+tdXEW+QzJejtoZX8Rgky1PQl9lPfcFnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T22:36:39Z"
    mac: ENC[AES256_GCM,data:xbynBWrz5sht21JwthoRCpBizF8blfzu6+gZZd72xcEOAmRJvrHwEt3ntQroAveVFTOpgX9g4yYSgjH8a9xr2BC0MUsiTuw6n6IA5WjsQhTgh/m8oiHvk8AuN2Uo0QTln7ErgkHDvwKaQMJJrDCkvdiQhRotCQXpF0u+GSxObwY=,iv:IIWJijxVLLHL9AU5abkI5grBnfNVbFhxQO4RPgsWoL0=,tag:UPZWDm6Y69PWew+iVpyznw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
