services:
  glance:
    image: glanceapp/glance
    container_name: glance
    environment:
      - ADGUARD_PASSWORD
    volumes:
      - "${GLANCE_CONFIG}:/app/config/glance.yml"
      - "${SVG_ASSETS_HOST_LOCATION}:/app/assets/svg"
      - "${PNG_ASSETS_HOST_LOCATION}:/app/assets/png"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    labels:
     - traefik.enable=true
     - traefik.http.routers.glance.rule=Host(`glance.homeworld.lan`)
     - traefik.http.routers.glance.tls=true
     - traefik.http.routers.glance.entrypoints=websecure
     - traefik.http.routers.glance.tls.certresolver=stepca
     - traefik.http.services.glance.loadbalancer.server.port=8080
     - traefik.docker.network=proxy
     - com.centurylinklabs.watchtower.enable=true
    dns:
      - 10.0.1.3 # DNS in `proxy` network.
    networks:
      proxy:
        ipv4_address: 10.0.1.8

networks:
  proxy:
    external: true
