# INFO: Generate machine key using command below.
# nix run nixpkgs#ssh-to-age -- ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub
stores:
  yaml:
    indent: 2
keys:
  - &default_ssh age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
  - &default_machine age13z0lq6rucrmmkntg6ww5ewtxsczg0q878ttslqzx0jwj5qxajvjsmldjyr
  - &lstr_machine age1fv4y2fnykau0xv6vaw57aw5cskyua26v2h63y6gvqjf530fc35fq9t6dp9
  - &klbr_machine age1zwzf8qudsj2g9xf2l84pmh45lcyck05fev99h6zc5j5pgsnlxqzqm8r4cl
  - &arar_machine age1cg4emjqm42wjll4sh03pasxp7ga658xx5tfqc90jsycg37t66aysg5dgw6
  - &falke_machine age1p0el9phnfxnjnaa9mgqtru4ke30vcae7vlzffmre2czf4r5w54rqwm8f0z
  - &mnhr_machine age1ustkwg4dht8hydkev74cdvp765aundsggutq66ndm5nmckuddqnqlcrv7v
  - &sapr_machine age1jsh9t5wfjv9extwpmwcwmv9gwdyw3z69lu67es2ttcl7mr58zdlsdpe7ju
  - &eulr_machine age17r8y3a9y0v6zcxzcstg3ypnq4skzc205umvsk63yrhuzw8z4zayqqeatcw
creation_rules:
  - path_regex: hosts/default/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *default_machine
  - path_regex: hosts/lstr/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *lstr_machine
  - path_regex: hosts/klbr/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *klbr_machine
  - path_regex: hosts/arar/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *arar_machine
  - path_regex: hosts/falke/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *falke_machine
  - path_regex: hosts/mnhr/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *mnhr_machine
  - path_regex: hosts/sapr/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *sapr_machine
  - path_regex: hosts/eulr/secrets/[^/]+\.(yaml)$
    key_groups:
    - age:
      - *default_ssh
      - *eulr_machine
