[config]
"secrets/dflt/wg.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/dflt/user.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/dflt/devices.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/dflt/syncthing.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

"secrets/lstr/wg.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/lstr/user.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/lstr/syncthing.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

"secrets/flkr/devices.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/flkr/user.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/flkr/wg.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

"secrets/arar/devices.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/arar/syncthing.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

"secrets/mnhr/ssh.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/mnhr/syncthing.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

"secrets/stcr/wg.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

"secrets/eulr/ssh.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

"secrets/iso/iso.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/iso/hs_ed25519_secret_key" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/iso/ssh_host_ed25519_key" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]
"secrets/iso/ssh_host_ed25519_public_key.pub" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIo8jr2hIBya3nwI++mqfs8MnJqXmHSQVPZUp9nhyVI1"]

