---
services:
  variance:
    container_name: variance-web
    build:
      context: https://github.com/mat-1/variance.git#7b79b8ab625ffdf8de09a96c3583f5539835bc26
      # HACK: Can't resolve some external hosts due to DNS is the same host.
      network: host
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # HTTPS Router Configuration
      - traefik.http.routers.variance.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.variance.tls=true
      - traefik.http.routers.variance.entrypoints=websecure
      - traefik.http.routers.variance.tls.certresolver=stepca
      # Service Configuration
      - traefik.http.services.variance.loadbalancer.server.port=80
    restart: no
    dns_search: proxy
    networks:
      proxy:

networks:
  proxy:
    external: true
