---
services:
  variance:
    container_name: variance-web
    build:
      context: https://github.com/mat-1/variance.git#96110dd5532dbba4591d265d4288ad7b3bb6712f
      # HACK: Can't resolve some external hosts due to DNS is the same host.
      network: host
    labels:
      - traefik.enable=true
      - traefik.http.routers.variance.rule=Host(`va.homeworld.lan`)
      - traefik.http.routers.variance.tls=true
      - traefik.http.routers.variance.entrypoints=websecure
      - traefik.http.routers.variance.tls.certresolver=stepca
      - traefik.http.services.variance.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.0.1.10

networks:
  proxy:
    external: true
