---
services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - linkding-data:/etc/linkding/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # HTTPS Router Configuration
      - traefik.http.routers.linkding.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.linkding.tls=true
      - traefik.http.routers.linkding.entrypoints=websecure
      - traefik.http.routers.linkding.tls.certresolver=stepca
      # Service Configuration
      - traefik.http.services.linkding.loadbalancer.server.port=9090
    restart: unless-stopped
    environment:
      - LD_SUPERUSER_NAME
      - LD_SUPERUSER_PASSWORD

    dns_search: proxy
    networks:
      proxy:

networks:
  proxy:
    external: true

volumes:
  linkding-data:
