http:
  services:
    syncthing:
      loadBalancer:
        servers:
        - url: "http://arar.lan:8384/"
  routers:
    to-syncthing:
      rule: "Host(`syncthing.homeworld.lan`)"
      entryPoints: "websecure"
      service: "syncthing"
      tls:
        certResolver: "stepca"

