{...}: {
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
      MIIBszCCAVqgAwIBAgIRAIHE4hhXCsPoL3cQOnCb31MwCgYIKoZIzj0EAwIwODEW
      MBQGA1UEChMNU3RlcFNpc3RlciBDQTEeMBwGA1UEAxMVU3RlcFNpc3RlciBDQSBS
      b290IENBMB4XDTI0MTExNzE5MzY1MVoXDTM0MTExNTE5MzY1MVowODEWMBQGA1UE
      ChMNU3RlcFNpc3RlciBDQTEeMBwGA1UEAxMVU3RlcFNpc3RlciBDQSBSb290IENB
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUNEVB7Ld6xfUg0expNZ9+IhL18M/
      0mdWkHVTpxW4m33Kpybi2Cccssf1R0aCPDHQ5ZNergxqpm+QRgA31ffgrKNFMEMw
      DgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFI+I
      Xw5Msa+5KTYUUgF6eozca88iMAoGCCqGSM49BAMCA0cAMEQCIGDEN/2jhY/TqzQB
      h1qezY0iBXRNNxEe1FktVGt/lJI+AiBlWpsHoKybE9jGc+y+gT4N/oVd84/vj76q
      meuBjvSfPA==
      -----END CERTIFICATE-----
    ''
  ];
}
