---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    privileged: true
    labels:
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.homeworld.lan`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

    volumes:
      - "/mnt/storage/jellyfin/config/:/config"
      - "/mnt/storage/jellyfin/cache/:/cache/"
      - "/mnt/storage/jellyfin/media/:/media/"
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.0.1.5

networks:
  proxy:
    external: true

