---
services:
  qbittorrent-nox:
    image: qbittorrentofficial/qbittorrent-nox:latest
    restart: unless-stopped
    container_name: qbittorrent
    read_only: true
    tmpfs:
      - /tmp
    stop_grace_period: 30m
    environment:
      - QBT_LEGAL_NOTICE=confirm
      - QBT_WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - "/storage/downloads:/downloads"
    network_mode: service:protonwire
    depends_on:
      - protonwire

  protonwire:
    container_name: protonwire
    image: ghcr.io/tprasadtp/protonwire:latest
    restart: unless-stopped
    environment:
      # Quote this value as server name can contain '#'.
      PROTONVPN_SERVER: "UA#44"
      # Set this to 1 to show debug logs for issue forms.
      DEBUG: "0"
      # Set this to 0 to disable kill-switch.
      KILL_SWITCH: "1"
    # NET_ADMIN capability is mandatory!
    cap_add:
      - NET_ADMIN
    # sysctl net.ipv4.conf.all.rp_filter is mandatory!
    # net.ipv6.conf.all.disable_ipv6 disables IPv6 as protonVPN does not support IPv6.
    # 'net.*' sysctls are not required on application containers,
    # as they share network stack with protonwire container.
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
      - type: bind
        source: "${PROTON_VPN_PRIVATE_KEY_PATH}"
        target: "/etc/protonwire/private-key"
        read_only: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.qb.rule=Host(`qb.homeworld.lan`)
      - traefik.http.routers.qb.tls=true
      - traefik.http.routers.qb.entrypoints=websecure
      - traefik.http.routers.qb.tls.certresolver=stepca
      - traefik.http.services.qb.loadbalancer.server.port=8080

    dns_search: proxy
    networks:
      proxy:


networks:
  proxy:
    external: true

volumes:
  qbittorrent-config: {}

