---
services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    pull_policy: always
    ports:
      - 11434:11434
    healthcheck:
      test: ollama ps || exit 1
      interval: 60s
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: cdi
            capabilities: [gpu]
            device_ids:
            - nvidia.com/gpu=all
    environment:
      - OLLAMA_HOST="0.0.0.0:11434"
      - OLLAMA_ORIGINS="*"
      - OLLAMA_KEEP_ALIVE
      - OLLAMA_FLASH_ATTENTION
    volumes:
      - "ollama-data:/root/.ollama"

volumes:
  ollama-data:
