################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  web:
    address: :80
    transport:
      respondingTimeouts:
        readTimeout: 600s
        idleTimeout: 600s
        writeTimeout: 600s

  websecure:
    address: ":443"

################################################################
# API and dashboard configuration
################################################################
api:
  insecure: true
  dashboard: true

################################################################
# Providers
################################################################
providers:
  # file:
  #   directory: "/etc/traefik/traefik.d/"
  #   watch: true

  docker:
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock

################################################################
# Certificates Resolvers
################################################################
certificatesResolvers:
  stepca:
    acme:
      storage: "acme.json"
      caServer: "https://ca.homeworld.lan:8443/acme/acme/directory"
      certificatesDuration: 24
      httpChallenge:
        entryPoint: web
      keyType: EC256



