user:
    password:
        hashed: ENC[AES256_GCM,data:TEAwCTcsSIG85E7Ap9hrMvtuIfI3Vxs0l+B4lRR8c7sVnxvrD+VrrkOLZDD/u+tFmZ5UhWSFaNsoFU4d/p3vKnUt3FYUrebP2g==,iv:yZcP7zEoM9vc9Bb9BLIOlhD9pV6A81/IthB+4e7zGmA=,tag:J8oaE+IPtR4ga199MwExSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1hjNHd3bUxyL01MUHVz
            a2FGa3hWUjgrNTU2LzBjU2tsTkRHMXhqcVRvClBnczlXUjUvandJTW5kdGc3Szkv
            b2psS1paNTJJNGNOR0dBbTR3OEtVb0kKLS0tIFh1REhLMzNqRk9JVHo1WnNCL1dU
            OTZ5L2tuMk5FN3g5RVY0ZmkzbVMzNDQK7UYrxUm3gwcMSEWBFbRJmObYko9RVS/G
            d+CRyA1sHjkurZ8I9cxtq9vo4jZwxYVkZ71n3uoUmhZjeV1xRaF3Nw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16punxsfd7h3atyanu53hlhrtakx8rmpqhc7q3udsxqncsvl08dqsksuevc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V0s2bFFWbHR6emJ5MFUz
            UDBwNjFPcU1nM1hkUHRNOGVEc3BBYTM4V3pvCmE2VEhRaWJPK01UWXNTSXBCVUlC
            aUk1R1E5bStSUi9nSDYxSTdLZmFmVUkKLS0tIEJxREhhcGE5TnJkNm5HTDdUTnVM
            QjRFbU1ieDV6cDFsaW0rcXd3VHFUcDAKhMT0hDIxDklpP4J/rJMfcTV3wuW47mgQ
            kYZUyXnDR6dKgDAUNH9daIQHJUTFh1O1z8HGNqZXqWCxgeU0tyFY+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T23:10:56Z"
    mac: ENC[AES256_GCM,data:Hc4+1keji5tk02dc17jvyA/JBnnwmU2sDxKnDoJzb9bsStxEvifCKCTT0o70EklD55Jpt5nzrKPzLIv5xEyx/hZ8OAryeQw1TZG3RSxH9qD5fF03iGeF5hNkfhLyNU1YJjYHUv+imjdTtCjxeHQEch1HEm58DFHm1m/qRcVm3oA=,iv:tZTrXmkqM2HhxZ4nKcqLSlWcbYuplJl9OpN7n26wiDw=,tag:L/vsoSBe9p4ZQYhLFTwjaw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
