# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  devices = import ./secrets/devices.nix;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/${devices.fs.boot.uuid}";
    fsType = "btrfs";
    options = ["rw" "noatime" "commit=60" "space_cache=v2" "compress=zstd" "subvol=root"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/${devices.fs.open.storage.uuid}";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/${devices.fs.open.root.uuid}";
    fsType = "btrfs";
    options = ["rw" "noatime" "commit=60" "space_cache=v2" "compress=zstd" "subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/${devices.fs.open.root.uuid}";
    fsType = "btrfs";
    options = ["rw" "noatime" "commit=60" "space_cache=v2" "compress=zstd" "subvol=nix"];
  };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/${devices.fs.open.root.uuid}";
    fsType = "btrfs";
    options = ["rw" "noatime" "commit=60" "space_cache=v2" "compress=zstd" "subvol=var/lib/docker"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/${devices.fs.open.root.uuid}";
    fsType = "btrfs";
    options = ["rw" "noatime" "commit=60" "space_cache=v2" "compress=zstd" "subvol=var/log"];
  };

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/${devices.fs.open.storage.uuid}";
    fsType = "ext4";
    options = ["rw" "defaults"];
  };

  swapDevices = [];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
