---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    privileged: true
    labels:
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin2.homeworld.lan`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

    volumes:
      - config:/config
      - cache:/cache/
      - "/mnt/storage/media/:/media/"
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.0.1.5

networks:
  proxy:
    external: true

volumes:
  cache:
  config:
