---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=http://ollama.homeworld.lan
    volumes:
      - open-webui:/app/backend/data
    restart: always
    networks:
      proxy:
    dns:
      - 10.0.1.3
    labels:
      - traefik.enable=true
      - traefik.http.routers.open-webui.rule=Host(`owu.homeworld.lan`)
      - traefik.http.routers.open-webui.tls=true
      - traefik.http.routers.open-webui.entrypoints=websecure
      - traefik.http.routers.open-webui.tls.certresolver=stepca
      - traefik.http.services.open-webui.loadbalancer.server.port=8080
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true

volumes:
  open-webui:
