user:
    password:
        hashed: ENC[AES256_GCM,data:7P9vC5bZcI3wsHbAcTdD48aoz8FiRhhf6NnzUxSLb40WW/wrzb4yNpU00ZEx5MgyUvykWh19dOzM8UTvBJPzaq4ZwgbIUFlPFw==,iv:zFHTtsR5AozIjOG3GAi98ZUQ0htsmKFwKER2FJ+g5Gs=,tag:ZrC3uYTmu+W/fTn7hGP4vQ==,type:str]
    keys:
        sops:
            public: ENC[AES256_GCM,data:iJedTfaVymkP1LtGfOwuITMmv/eZlwZRGlaqZztIk82Fr+D1JLccyRhWceLEQfgaIT9pWdZO5QHjsRs4Q/g=,iv:GRzgnDl9J3lgCLjQ7eOKD2mFQn1jey/QAbOVo8XKDq8=,tag:Wzb+oAEJYvOmf75VR72MEg==,type:str]
            private: ENC[AES256_GCM,data:dEiKp8MJCjBlObW0+unhsg5I3W8zLuEImQkqP5HCk0pTokF+trHM11eV/hvc3G4vsxNUAho3CK9xppqZNFlPSNUF8DyEFKBKq+Q=,iv:WdaBOImxkQ6Ijnm+ub6DHMSB9ZdP+ofN2ZsR5EVrPZQ=,tag:i/Q/Np7mAWC1IRKQfMlCZw==,type:str]
        ssh:
            authorized:
                flkr: ENC[AES256_GCM,data:9/DVK1uBMmJ9X6jL6A6smt5jXhrPCJwNTYaIEBg2EraK5C7bBAtBaOuwKgZVbh02KbomdJSAEQUDix6RYw/ZEEix7Gh4y6ayndg9qDKuDXo=,iv:HTzNby37jIYYwt7d/3i+MUHBSKjKWHNWPRNj20dNnbo=,tag:18QPUX/+KZLpRjeQOY1omA==,type:str]
                eulr: ENC[AES256_GCM,data:C0lCkqx7oDQX0AFMARgQ7WNSK3doUdab6+QO7mC2GGkHR1t71eGJsoihnk8BqXFZjuv3kr6boMWfAR7amTFXhlNhIPQUl5lEVvEKhXpCfRk=,iv:JP24WMtIy2ogkbJ7+QvgGCFH2RdJwlxHAMyOLgGQz/c=,tag:4HNi2wAAkOg+8n4iUQXOSw==,type:str]
            public: ENC[AES256_GCM,data:SSazBkXGM3SsW2EGRlzCDSYtbCun43WnOuHLR95IKiFIC4eormRKpPS2YRhNwfQ/5N9RLuulSPCjShD6F2DHloSZBfH+QOgjRtBiTvEyHDo=,iv:t4ZYjarW8d2hbvpwklf0V8UziWF9b/PkP2ah1A4y8xM=,tag:FKK11/ygWHakmi90MzpV7w==,type:str]
            private: ENC[AES256_GCM,data:8CHjuqbwCaY7ZISeiQNR4TjhL10CMGnqrOEnbfwFfv43nM77Kzizf0QM4rUBMHlctW9+v5WW1d39lhaEC5u7jCa9K4In1rFAGivQ5CQGz5KZYDP+kRf1AmY3CAZAgeXC4JWR+tixiYrGLxCTjhon01IpmoiQSxYLYu0LFaRTJh1usHVr79j5aA2Qm5RCXgKOvpYhGjHozOuyQTkL9dw/i/GIsX2BSZktuwjg/97zbULlBbE86odCLnCZ/nvDyOAltNgbX5DjGRCYHAJQvjJO/b1o7YbhnRF6XcRYxh/d05EA69nxVCM/TKg4Q0pubiLLBk6KiRThHJbelDUj5GbOwmURx+Wa9okJhZiL3B3PXyv2n39rDtnWlsvWCnQCFV1wKrCZCnT1tFprfv578Whlmf5HTkWOC8kb3SUcfHY2HNBUkgTMZvXORdaxTph2h0JQjFaGBbnKevCK09SxaqcLa+hXBcdc7jmmXhhxxVJC5Np6Pa8uSIwl3PmCQcWBQPrZBGlWpFUeH75ZNHhQC+IW,iv:FBAufE9Qj7FStE29wHpT68A+Kz2e08P1FBLf+abUn4w=,tag:kyjseL/hQ0opgdKFn52ezg==,type:str]
sops:
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcWY4ZnNHVjdYWTN0U0VW
            MUNxU1NuZngxT1huRURTSENjNDQ3UVJJT0V3Ci9SWk5iNWNKSloyNjJPcVlFUWJQ
            UVRkSXIyYkxiai85VC9oTDBkcFZ5bUEKLS0tIExtUUxwQUJqaFpPWUVISVBiRjJK
            c2tjT0xJaWxuS3JVL3NDOUcwRXhnWTAKfe2/FS4CoD3+cCtGmPPkTIlzK0FbJtcd
            NegpzKovKVXBdpRxdkOUxee/njxXETy45ybBEU0nDuIyQFgxqksAuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fv4y2fnykau0xv6vaw57aw5cskyua26v2h63y6gvqjf530fc35fq9t6dp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWWFJaDZlT0pBS2NJNE5q
            MWs3dkttbTUrUTBYTDZQbWVWL3hPNHd5dWowClB0cHRTUW92SGhST2RtaFZIbWNQ
            Y0J1UWJlUSswbnFVODV0V1o5ZG1uMFEKLS0tIEd0QytsZmhqOWVPOHBFblhOVnpU
            QlB2Q04xRWtlTndQc3o3Y3RIWk5YT0kK4hCa6pnaDqPdAc0rNp/QW8JIYmP+F7WL
            Mue8Rnnujnu+LygoxjFly9UN0gH2/+lmxlVpN9e8rmgsLuq4ubQ45A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T01:19:55Z"
    mac: ENC[AES256_GCM,data:R4WNql7NX0WXSxoXazxMtw7f+PoVL+7L5oPcYvXjIDqU7mZ4hbRU5IGSaMXO6oiTzAtwMw6oXUAjSj+3QTqk/BG/vyDE1dyMhzP3wAkr/b0/cVcGdwWCs242pd0FGVnL5+lR31hDSulmZ/3xFy19OYzJFSDZ4wviGCOXfSD8a+I=,iv:U82J2ociCGULgxSMM0HWtj4Mo0jRF9W52YYyAPSPVIE=,tag:sgQFfKELONCpwy1CizK+sw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
