user:
    password:
        hashed: ENC[AES256_GCM,data:0YMWlFzkpbG7ct2aM57Pm7/e3RsH3Z3JSSFGQeU85YyZjlnyYQjTz619q6D4XeqYhl4XaYMBGlxrdif6OCx+gR7Z//HOyTMhIQ==,iv:+GP7DZVeDXJ/ufTCLwghfIw8e1+yAKChwc90y38joMo=,tag:J4w62gi0fnAhYyS/ys1cNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTVlESzFUS2xLN2xVZG9G
            ZkFmWDltUDhXTWt4TFFNQUVaYlI2bXFTOEZjCmxUbzh6VDdXWlRUMmVPbDJzWlAx
            bys3RWRxWDkyNENZY3dKcXdyNkZ6Y1EKLS0tIGt3Tm1uRmJSMGEzK1l5OFQrTXVx
            SzBDdmxvcGZuTnhpTUE5WktOSzRwM00KuUFa25oMcDl6icvZRTXy99euZ1NMc620
            Rbc1YHhjfVK+B7OlxaLgcf/DtOWMmh+q71NlqNDTBQlr9+oYMYiOTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cg4emjqm42wjll4sh03pasxp7ga658xx5tfqc90jsycg37t66aysg5dgw6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdmJkb1dIYUtOU0J1T2hu
            QXpDUmdBamx4K0VnZ3F0cEVRRDhvOWFyQ2c4CjZ3OSs3N2lZVURVaUJwQzR1WE1K
            Mm1yWER5bHZqT1h4TFAzMG9MbUc5SW8KLS0tIDhmRU5JZVYzL3FpV2t1QmZMc2Ev
            NG0yZDJ1bEhBbmQ3bnl4OGs0d3lPaTgKN+YzUvuDMV/axadVcxuapsEFHmFHXQUJ
            UzjUdo9a4EB8xL0hG1IPpRPPkeI8nbBzLYFSBXjp8hHtaLwYByBkfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T00:00:23Z"
    mac: ENC[AES256_GCM,data:kkEIB/Mj/ZqyOm4fW5l4ZEoHlg2Y5eNwKD2aBQKGaIL9oIf0QQeufCkQ5faNUqEpA53gzi66bLGgG1QYyGdhbxKdBFsvWiaJyVNW6V4S1r6IlW45zDhHyEqiqd9QZR6IDrllskz1y4llPu68EyoZC2LdnJAqe00niWsGCzLbzf0=,iv:Lu3fiIOEqpI94pQIcw5cHk/sf37x8Rg/jcccpn9kfuE=,tag:Qjc6uOvJ1CGxz1KB8kxfSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
