user:
    authorized:
        baseship: ENC[AES256_GCM,data:FHCjbqviAWnidaTYMOawa9ZljaRIKLZsk6tKx5DnIy7eGjVED1ZXQFAXR8koy+lRJn/VG1kkz7EiUlarsTTJEMU4bJcbAsnJ8vKaZ2P45W4=,iv:mz/3LsuM/T2gE1fUlVq7xmBcYLmh32EujpsQEI3dgVU=,tag:3TJszh/jk84u86e7VT8RSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSnZZSnZsOGhmSTJLSjNC
            QkpJbTUySmNWRVFxMmUvckN5UmlPcWQ2bHkwCnFvYUliWEFSN2RMNGhzaHhkTTRw
            RU1CQWx3NExWd0l2Q2VqK0lxWHlENk0KLS0tIFFrN1NWQ1NtS2lMeVp1cjVSRFVW
            ZFdlVUxZSGxwYlVnbnJhR1V3VXcwQ3MK+GcFVOJmycxoLF8jUcLzN4gnvv/VnHlV
            eCpx5voNdMUT6j2JRHBGi9gLl5lrZavIC8vU1pH3XxLMp8Tx9xx/Ow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17r8y3a9y0v6zcxzcstg3ypnq4skzc205umvsk63yrhuzw8z4zayqqeatcw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS0Myb1MxU3NINUxCUFln
            MWhMZERWVG1lMU1WbzVZbk9JL1g1Y1VQNmg0ClBxVnlBRFJCdklMTUFISDdOVjJk
            M2dIaVh2SUZIcjdVS2tFOTNraWtCL3MKLS0tIFhWWjRpK2h4dkhvR2pkeFpzZFFM
            eTFTSW0zOTRoMFpOUXBES2tiNzZPUU0KfdnuqFTVSEBHQWcx+nYvhk55VZ8gkz1L
            zsIe6qv0keHeCDEiQmtSbwd29hjt0Ld+CcPWL/fCf78cXGq7JN3CZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T00:14:49Z"
    mac: ENC[AES256_GCM,data:7SzXymfw44UOk5HREizzWOqcROlcncWjopFvWoAGgOvI7YCC1S7VYSA72jCd4Bqlx2VkutlKLi320tU9E6PHOVFf52dxq700JIWQHAwoW96W3sR1TErcPqAGHM/kVNIskdP5GqSfAgOVxK4ZgowusgHKda5OAy0PvRJM2jHJs7w=,iv:lzcyWZQGTV8PBVaeB9JyCS0ASeskkyHYdcgLNjgMCWM=,tag:/6tu3h64rUK7Oud6eGruLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
