user:
    keys:
        ssh:
            public: ENC[AES256_GCM,data:JPa4+s3wX7017orEwusRAOFiuyzCcgiFrwHfArKqrcmPOf30rqee8D7mK6AxKgzdmpxlMp5GFpvKXC9BkSXq76fD3P/P11ifn5lNQHXXWAZir7m0VBJjHqHJksoq1g==,iv:VQCWu+Sny9RQzTUalM2k9OGI3wLwS/OV5+aRt7qMEmk=,tag:AcPQh+j1a8HIvNj7hlXB1Q==,type:str]
            private: ENC[AES256_GCM,data:T8QfCAYOG5ffxCWWBWQVGr4B06KYJxoWVoAeKbf6S+kAcOPIcZZkIsC+wLJqLUmlpFOk/OWx6GEe51fEkyDjdEQSk9tSzXoTx0RBSp1M8zh97EB/LVNf4JSI3+IprhzinEAvAbyoswkXdCouSCT5UeDp/HNMmkPmqnh0YDq+lobJ1bpfBsUgSdHnF7O5azho+3gRvSYbNfJy99BTu6xsbDTHUqcQxeq8Z+c5/7cnV9XTbAzYQ4/BmTVN099OV83vGd3cpj6BTzzzfSFxMuLx7MbaJRGcCqI/vWobe6W5RrIxKa5B4ygZxKgJ3SV55oULUGyQc0yB/xpQwUaJ0PQJIrzHLngGxnOOzlcLfqaOM5N3kfEZtIVR0WquZBNSam9YDQgHmWo+OsU+blMszQO77zCBNa9proIrYz4uZEZCGhYETr0z7FKtX8Mxxdg5agaHMyKbZe58mrW0DvrNVrqZNXAk0Die7qZ6YkQG95/E7JFe1UmLDRtrZoI7tKkFzfTfO3c+wg7v8QpfhH+nlRG2BLilqapW0bT6vkNKPoLc4O8/xEKoICpmdaWnRh8XO1ucFoD6wGZQot24VOG3,iv:/J3BM62uwBu5cXxCNlNfCQP4wal3bqCucD3zyaGvgoE=,tag:Zci5qnWkhy4Jg0RPUA0iIg==,type:str]
            authorized:
                baseship: ENC[AES256_GCM,data:YD35Y3gTCsfbOFqX28SVsLbBxWzdX/yEno0XkQw4fTfYSZ2lVBj6k4jd4AVYWvmF+1IhGuh3EOrh4xh2P49bnMpv6Mu0Ja3QEovqkcBU2x0=,iv:ozdLMKCLF2KddcktGSVlMPQmytATiV4hN4lJZ4jhqpk=,tag:UdnNzcBqtpcv/nbT2xGY9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSnZZSnZsOGhmSTJLSjNC
            QkpJbTUySmNWRVFxMmUvckN5UmlPcWQ2bHkwCnFvYUliWEFSN2RMNGhzaHhkTTRw
            RU1CQWx3NExWd0l2Q2VqK0lxWHlENk0KLS0tIFFrN1NWQ1NtS2lMeVp1cjVSRFVW
            ZFdlVUxZSGxwYlVnbnJhR1V3VXcwQ3MK+GcFVOJmycxoLF8jUcLzN4gnvv/VnHlV
            eCpx5voNdMUT6j2JRHBGi9gLl5lrZavIC8vU1pH3XxLMp8Tx9xx/Ow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17r8y3a9y0v6zcxzcstg3ypnq4skzc205umvsk63yrhuzw8z4zayqqeatcw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS0Myb1MxU3NINUxCUFln
            MWhMZERWVG1lMU1WbzVZbk9JL1g1Y1VQNmg0ClBxVnlBRFJCdklMTUFISDdOVjJk
            M2dIaVh2SUZIcjdVS2tFOTNraWtCL3MKLS0tIFhWWjRpK2h4dkhvR2pkeFpzZFFM
            eTFTSW0zOTRoMFpOUXBES2tiNzZPUU0KfdnuqFTVSEBHQWcx+nYvhk55VZ8gkz1L
            zsIe6qv0keHeCDEiQmtSbwd29hjt0Ld+CcPWL/fCf78cXGq7JN3CZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T20:26:11Z"
    mac: ENC[AES256_GCM,data:R/6rlM8r5M2YRN8ZZGsqXt7sTgQ6+G6gsIC+iXoswjAM8O7rGtKKyz6ryLSSdDpRLT8JP9IJwxotHGdWyArDmayXjN/eNGRqNn/oAiRDzPkUGjetwKZuRBDAaGp/TPkNFwXwKVXYY4SNTkklsePxllEYTVr1i9B5og5EBHaZ2LQ=,iv:vDONf932SDtOAGIxEiN5QeYBJmvAfVZXZP6sjYT0vBE=,tag:5CJWc4Luawn8WtS2Usvt2w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
