---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST
      - PASSWORD
      - LANG=en
      - UI_TRAFFIC_STATS=true
      - WG_DEFAULT_DNS=10.0.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - UI_CHART_TYPE=1
    volumes:
      - wg-easy-config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    labels:
     - traefik.http.routers.wg.rule=Host(`wg.homeworld.lan`)
     - traefik.http.services.wg.loadbalancer.server.port=51821
     - traefik.docker.network=proxy

    networks:
      wg-easy:
        ipv4_address: 10.8.1.4
      proxy:
        ipv4_address: 10.0.1.4

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Lisbon'
      WEBPASSWORD:

    # Volumes store your data between container upgrades
    volumes:
      - pihole-config:/etc/pihole
      - pihole-dnsmasq-config:/etc/dnsmasq.d
    restart: unless-stopped
    labels:
      - traefik.http.routers.pihole.rule=Host(`pihole.homeworld.lan`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.docker.network=proxy

    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
      proxy:
        ipv4_address: 10.0.1.3

networks:
  wg-easy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.8.1.0/24"
  proxy:
    external: true

volumes:
  pihole-config: {}
  pihole-dnsmasq-config: {}
  wg-easy-config: {}
