---
services:
  deep-research:
    image: anotia/deep-research-web:latest
    container_name: deep-research
    restart: no
    dns_search: proxy
    networks:
      proxy:
    labels:
     - traefik.enable=true
     - traefik.docker.network=proxy
      # HTTPS Router Configuration
     - traefik.http.routers.research.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
     - traefik.http.routers.research.tls=true
     - traefik.http.routers.research.entrypoints=websecure
     - traefik.http.routers.research.tls.certresolver=stepca
      # Service Configuration
     - traefik.http.services.research.loadbalancer.server.port=3000

networks:
  proxy:
    external: true

