services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://${INTERNAL_DOMAIN_NAME}"
      ADMIN_TOKEN:
      ICON_SERVICE:
      SIGNUPS_ALLOWED:
      INVITATIONS_ALLOWED:
    volumes:
      - "${VAULTWARDEN_DATA_LOCATION}:/data/"
    labels:
     - traefik.enable=true
     - traefik.docker.network=proxy
      # HTTPS Router Configuration
     - traefik.http.routers.vaultwarden.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
     - traefik.http.routers.vaultwarden.tls=true
     - traefik.http.routers.vaultwarden.entrypoints=websecure
     - traefik.http.routers.vaultwarden.tls.certresolver=stepca
      # Service Configuration
     - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    dns_search: proxy
    networks:
      proxy:

networks:
  proxy:
    external: true

