user:
  password:
    hashed: ENC[AES256_GCM,data:TwL0ZPCdrkHs563iUkWFwKT9gHsPRS4a8nRsBONxAGGNtz/X9CUNw8/OKOKaJpQmkGeq5Jl/Fcdbu4jQhUls75ras7uEtKC4hQ==,iv:DmpNu3OFneVeA/TbEKYsS++gZp18RMzsEL4odOaaOz4=,tag:GgVdRdGNspJG3niSARrhPg==,type:str]
ssh:
  authorized:
    lstr: ENC[AES256_GCM,data:/xysBuGNZ3iPyc0mTuZBXjyqYDA0LwVcO4t2FDaRmqgsKZmFxRcCe7WQzMO4GXM86jVVzMrtSV6ZOYZKs3GUDIJBXE/4cni6QNp+lwygQ2c=,iv:ybc5qHsjeZT9PBsd2nONprrXiAZPYU1NMZN3UrsF1Cs=,tag:sromTJFWiOtC0BqppKuN5w==,type:str]
sops:
  age:
    - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc3BzeHRWMlVOVkJWV0hL
        UlVma0oyYTQ2NFRETHZMVnA1Y2JzbU1STDJzCjJFbkdSUFhnWVY1S0crbmhLZWkr
        YkFaZUdwTEpHTnl3YUFvcXBCWTRmY3cKLS0tIDg3WTJCOE10alBMcUFyV2Vjd3Uz
        T21XOWdBRFV2RHNHcUZmTmpZTHdJUHcKs1tsYrhDdAEgLy3hhFwnm5KiQuanElBA
        jRWQloZEL8aKq/vo4vRtNCquhPN8ZVO3DLmae9wG6cHOxFH6y2J1lQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1425z3trmzjp0f5kh4vdueevdhrd5zrzl6tvrztpelx377hctyvasvr8pn0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dEFwcXM0UTdkRVpkVEIz
        NllhMmp0T0pIZHQ4bWtUQzN3NzNNcktxUUFjCmUwZ01MOE13dzh0WmV3d0tIRzFx
        L2VMeENTa3VDV28yR1lHTUNGMHVqWmcKLS0tIHpyb1ZYa1ZZMG4wM20vSjhCVE9W
        UTFrQldoeTNJNTk4aXR5U2NDMDhHQjQKKjobJlWsIzLI6lJwe775l7wWGoDfRnpz
        1ZQTWE9baLO2DAf+tJRYeZFR2rUHPFwidtYHi0Qpe/vrRKjm1/6ytA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T03:33:00Z"
  mac: ENC[AES256_GCM,data:aXfwV79OcaisQMcNNAOk5wG5eBHEU6TcZPfcKTolAgKfwaBqVDyAI20oagsXluz9Gfrzj81GVc9/Qg4KxSdZbri6WQh7IM4m/Y8iQH5am/Bgqiq9DyHgNfpDprfCn3LfV3hetQaMP0y5RpF41oCJ42FirzkongFKDsqihEgoTac=,iv:UFqWox8fIeSbiy+EbAtXttCW8VgoIu6ZDW24jIXJoEo=,tag:WdA2Swf1EzX/OLKZrFxmkA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
