user:
    password:
        hashed: ENC[AES256_GCM,data:7P9vC5bZcI3wsHbAcTdD48aoz8FiRhhf6NnzUxSLb40WW/wrzb4yNpU00ZEx5MgyUvykWh19dOzM8UTvBJPzaq4ZwgbIUFlPFw==,iv:zFHTtsR5AozIjOG3GAi98ZUQ0htsmKFwKER2FJ+g5Gs=,tag:ZrC3uYTmu+W/fTn7hGP4vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Zyt6ZmdZOEVDZ2VPdmFv
            Q0MyTlBKSy9lODJ6NWlpdTBPSlVYbmo0MEFJCnRrNXVXem1VUWFPNXBBdzhNbEVh
            eG1TeUVTUVNlWFlHK1puV3JIZXl6Yk0KLS0tIHRCbFBuNTh6dk9IOTFQMDYrUXJJ
            NWgrOXJHVnVaeC9zYTBYU2lzeXlyeWMKBBPFo1BlfFraDIhrx51Z+zcqMrg1yIm/
            fiva0vC3AqN7IgXE6aW89TSaAI90oERAwmWaHUBlguZth05vb98SZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13z0lq6rucrmmkntg6ww5ewtxsczg0q878ttslqzx0jwj5qxajvjsmldjyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYlNLa3hiODB1bm50NlI4
            Zko3ZEUvZnVzL2VMc3pZQzZiTTdVV1NRY0ZnCm1zVkJSdWZReGgrMkJTSnM0RFVC
            VTcwbmc1Sjlmb2FHM3dvL2I0UW9QVncKLS0tIC9uc1pZYmRvY1VZdUlMTFhzeTlE
            WUV1em9IWEJ5M3dhZnhWejVhRkRBYUUK550G74wXdoA4nvWQ0GABks5oo9kZ6wRa
            gOFEScaw/96eeQlyiaK2XhH8hGez4tEqHdQ58JTfCrdCba9uP9KbtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T20:03:28Z"
    mac: ENC[AES256_GCM,data:2pT+JIxIowow4qKjkpIta11AbWDERhWecZVgEAOsLKva7sOwkVZNF3vasveSdE4LWayPSz5yQ1oCNLJQxuZAZQnVliKjyPHe24YY+FWhFYYF6KB99U4UnoQaAAYB/D483tCembuU/+hpo1zabUXwfzAVBdm6ardtx/0aJQTyhQg=,iv:JIvmN4uLN3io4uKzg/Ek5ufoYLmUXX4H25n1WOt0Bsc=,tag:xILK93mN5Qitw5sMkwoUDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
