user:
    password:
        hashed: ENC[AES256_GCM,data:7P9vC5bZcI3wsHbAcTdD48aoz8FiRhhf6NnzUxSLb40WW/wrzb4yNpU00ZEx5MgyUvykWh19dOzM8UTvBJPzaq4ZwgbIUFlPFw==,iv:zFHTtsR5AozIjOG3GAi98ZUQ0htsmKFwKER2FJ+g5Gs=,tag:ZrC3uYTmu+W/fTn7hGP4vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU1R5NHphNjNxdTg2Q0Ro
            RXBDUXhEbWxIdHdLRnlQMGlGZm9NQWRqcVdvCkladkREemZzOVBpSVh3Q1FuVndR
            R3lpaThWdWkvQW9pbFZpNHVQa1JaaXcKLS0tIDZsc2JpNjFHclJYWEoveG5OaHlw
            czRYc1Q2L3ZlSElyZjJZZ3BhTjQ2amsKsXgNZuncvyHMPrl3oOqB+FAFdsKfUmJP
            rZdZJQ55WI3f8keM4vDms+jsNi0zwPaXYF7XjTOFYTCICM7j4tMtdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T22:36:39Z"
    mac: ENC[AES256_GCM,data:xbynBWrz5sht21JwthoRCpBizF8blfzu6+gZZd72xcEOAmRJvrHwEt3ntQroAveVFTOpgX9g4yYSgjH8a9xr2BC0MUsiTuw6n6IA5WjsQhTgh/m8oiHvk8AuN2Uo0QTln7ErgkHDvwKaQMJJrDCkvdiQhRotCQXpF0u+GSxObwY=,iv:IIWJijxVLLHL9AU5abkI5grBnfNVbFhxQO4RPgsWoL0=,tag:UPZWDm6Y69PWew+iVpyznw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
