user:
    password:
        hashed: ENC[AES256_GCM,data:7P9vC5bZcI3wsHbAcTdD48aoz8FiRhhf6NnzUxSLb40WW/wrzb4yNpU00ZEx5MgyUvykWh19dOzM8UTvBJPzaq4ZwgbIUFlPFw==,iv:zFHTtsR5AozIjOG3GAi98ZUQ0htsmKFwKER2FJ+g5Gs=,tag:ZrC3uYTmu+W/fTn7hGP4vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU1R5NHphNjNxdTg2Q0Ro
            RXBDUXhEbWxIdHdLRnlQMGlGZm9NQWRqcVdvCkladkREemZzOVBpSVh3Q1FuVndR
            R3lpaThWdWkvQW9pbFZpNHVQa1JaaXcKLS0tIDZsc2JpNjFHclJYWEoveG5OaHlw
            czRYc1Q2L3ZlSElyZjJZZ3BhTjQ2amsKsXgNZuncvyHMPrl3oOqB+FAFdsKfUmJP
            rZdZJQ55WI3f8keM4vDms+jsNi0zwPaXYF7XjTOFYTCICM7j4tMtdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T20:03:28Z"
    mac: ENC[AES256_GCM,data:2pT+JIxIowow4qKjkpIta11AbWDERhWecZVgEAOsLKva7sOwkVZNF3vasveSdE4LWayPSz5yQ1oCNLJQxuZAZQnVliKjyPHe24YY+FWhFYYF6KB99U4UnoQaAAYB/D483tCembuU/+hpo1zabUXwfzAVBdm6ardtx/0aJQTyhQg=,iv:JIvmN4uLN3io4uKzg/Ek5ufoYLmUXX4H25n1WOt0Bsc=,tag:xILK93mN5Qitw5sMkwoUDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
