---
services:
  kitchenowl:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowl
    environment:
      - JWT_SECRET_KEY=NOPE
    volumes:
      - kitchenowl-data:/data
    restart: unless-stopped
    dns_search: proxy
    networks:
      proxy:
    labels:
     - traefik.enable=true
     - traefik.docker.network=proxy
     # HTTP Router Configuration
     - traefik.http.routers.kitchenowl-http.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
     - traefik.http.routers.kitchenowl-http.entrypoints=web
     - traefik.http.routers.kitchenowl-http.service=kitchenowl-service
      # HTTPS Router Configuration
     - traefik.http.routers.kitchenowl.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
     - traefik.http.routers.kitchenowl.tls=true
     - traefik.http.routers.kitchenowl.entrypoints=websecure
     - traefik.http.routers.kitchenowl.tls.certresolver=stepca
     - traefik.http.routers.kitchenowl.service=kitchenowl-service
      # Shared Service Configuration
     - traefik.http.services.kitchenowl-service.loadbalancer.server.port=8080


networks:
  proxy:
    external: true

volumes:
  kitchenowl-data:
