user:
  password:
    hashed: ENC[AES256_GCM,data:TwL0ZPCdrkHs563iUkWFwKT9gHsPRS4a8nRsBONxAGGNtz/X9CUNw8/OKOKaJpQmkGeq5Jl/Fcdbu4jQhUls75ras7uEtKC4hQ==,iv:DmpNu3OFneVeA/TbEKYsS++gZp18RMzsEL4odOaaOz4=,tag:GgVdRdGNspJG3niSARrhPg==,type:str]
ssh:
  authorized:
    lstr: ENC[AES256_GCM,data:OTmKp6slbedKhSWLSdHYxb+M1xKMXqen5O3j1Bq/Yhopo3pJkTxDY8fwGvGqJXHL7H6rwqjgLrtjByby+nULS5aRJzmVMCIq5q6Rk1log/M=,iv:xLoJKLQTdJBuHdOaN5WDQSUQvm8FVhSKtlk/xZa9h6I=,tag:YNkI1zU+jDJwkR786Cj/Lw==,type:str]
  host_key: ENC[AES256_GCM,data:Kdi7cH7Tu11ZUnW7ilQFRtuCGFXJTlsRm1dSITeNPcD/qHg09RxuFBT6VH9uwAr287BaviwaE4jaq3SR60I8X6pz+h06rAEhAZX6kINNILROfP1+yyKoRZMoE2laN06q+s5jjACp0snzLAoP/J1tIZzJdL9EAe1D28k/YY77Fi2iNZBsnYa3HH9+eDo/cPOcDlZtcObZFOfvffwGiI1QTFUDelHeVYco2bVKdEDjl2XjEyGwznl/37lPDYFrdhiuitjMsGb8m5e4AtLVTNdhxGOYbsGMWMz1Hx4ZNEyI3shKo4QKF0iDSSgdgNOkuAgivqhmH77By9xH/maRTi4Kf9C1mmSSp9XzbPcZOUcU3w4g47kJy44/39OW8WoWSZ0R8NFHk0lYoIqLV0a3kKbpxUDN86DZ0sOVwOzhYZdd0uUiMpsPgpnO8l6QdpPj1sVUTCYfPicsr5Y3e4H6K5JR7swPzPrWLp/O0HqEhpjrSJSmaJHhFFQNxXNJ9n0lhStdGn1jI5xJLdmhTyJTNffFmh61mZ3lFlHTUSoA9g1C92/98Bs=,iv:/xaNL18dWjhhbF5dFbwbax1ENLrBGi1dCVuqT8b2b+U=,tag:HLyn09slnkB72uaBUCeUQg==,type:str]
  host_pub: ENC[AES256_GCM,data:i5tNpg39qr0vBnQtaR8LOFAakahEmHxyOIDDw8rPFcw8jIWO5M3Tb32Hc6Z136SwUCDX8BRfzIT4Kzpvn+mKEamWJwOAXNpsoFJVSVesk4BSYZIa0PTyvNjcZccBnyyE4WmQ1a4VQx3I,iv:gGNIrVVonzfsN3SoU5OOQP65xPNDpwhG5EVGioMS4go=,tag:bR2pIZWxrUVCArq0wqmCDQ==,type:str]
luks: ENC[AES256_GCM,data:BQOQUegrbXmWHbcvo7/qcJGjinZoIMb8Qeq8BYy6FinMYk0shIMRRFPE1rNlpzuO6RYglmMNCAk0nj4ljk8am8LTxqfAtky+Jou1ojsYexi6r1kVJAbszIrQlCwMlXWi1C0CCoCRSh8aH79ahyN57V30Ee744PnUSj9nDQmSlsx9uTtm7odayOEtl6Y3MiHJ+hLYmzXonpTVB2NqK6GNmb84N9MmYaypQy/PJS81Si63Sl7xiOAB57ARKDOC3916LVdCRAanrwReJwKNu3hBwzoqOVKcPvoaR2Fx6jewSC7z2GONl8o0idBIaHev6YVP/849GPEQMqpBefWaJMGGJQ==,iv:5qSWb4qv7vqbC1ywdl294x7RpZ/04mGQEeCvzDZPQvA=,tag:J3lMBwAy/8GM8IDI9GRMnw==,type:str]
sops:
  age:
    - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWTlkZjh2dHRBb0lOWEcz
        UEVCNWQ5M1ZNWElDTGZZa0dBRXVYRHNKeURRClJBc3dweWRTQXpxd0JDdlJEWXFl
        SWZaNWMyM0h6aFZyOWJDNWFjY0FuU2MKLS0tIFQzQTNPRThnVEJpZ25iVzhnQitn
        SlhKVEN6dXdCeFcvV0VIcWxhRStLOUEKq89wtnIpRt0NoMNpoTPgOLr2rpM2X43O
        b6+LFUrg7Yf8hswWoTI7+GxO9GGpowHC8kOjICk0GvzQVrUlUVDl+w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1fjalfd7re6v27pfuxxxmg5cfvc2xavctmake59r293k80acvea2sdf086j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRDNNai93K0h5YUM0ellj
        bGk4Nk5CdnRBSE0vc1Z3T2VoZ0kwa2VyNnhnCm1WOXc4dnNZK3N5OS9Mb2gvU2Y1
        YXRMNm9VcVltNlAzZURGUTFVcG9KY0UKLS0tIHh2Ulk5TGorNHRoQk1CdSsxWmd3
        bFF5cUNIRXVnNWZhU0ZMOXdPU3QyOU0Kci4/rVI7rkMB1s7vWZdbgWg8p8FvmcIU
        YMtWU1VZUwujBiJBBe5l6AWbzeJawd/e+Q2NljCsaA9uojTG/rLCyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T22:51:46Z"
  mac: ENC[AES256_GCM,data:Juaqrz6RyczlSzDtBoou4+MfEyRi4wbR4tcpAS6nPJ/+pXsTZgTLIqIK0J84RuBRISiYqztsldrdHSOePfs1ErZ2Ko7luYdFPUgsQKyXoy9vql2wSoHOM5iyF62YBJ/xJl+503Jht9fZ6IEuCanUvy9F7vQPVbQyICdcpHm7Zrc=,iv:XLU/LviRdAXCzq40Zqvx2RxNUXjUy09e8h46vh0xX1U=,tag:1qzUNcAzajQU6XonbdYdOg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
