---
services:
  grocy:
    image: lscr.io/linuxserver/grocy:4.4.2
    container_name: grocy
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=100
    volumes:
      - grocy-data:/config
    restart: no
    dns_search: proxy
    networks:
      proxy:
    labels:
     - traefik.enable=true
     - traefik.docker.network=proxy
      # HTTPS Router Configuration
     - traefik.http.routers.grocy.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
     - traefik.http.routers.grocy.tls=true
     - traefik.http.routers.grocy.entrypoints=websecure
     - traefik.http.routers.grocy.tls.certresolver=stepca
      # Service Configuration
     - traefik.http.services.grocy.loadbalancer.server.port=80

networks:
  proxy:
    external: true

volumes:
  grocy-data:
