---
services:
  nodered:
    container_name: nodered
    build:
      context: .
      dockerfile: "${NODE_RED_DOCKERFILE}"
      # HACK: Can't resolve some external hosts due to DNS is the same host.
      network: host
    healthcheck:
      disable: true
    environment:
      - NODE_RED_EXPORT_GLOBAL_CONTEXT_KEYS=true
      - NODE_RED_EDITOR_THEME=monokai-dimmed
      - NODE_RED_SETTINGS_JS
      - NODE_RED_DOCKERFILE
    command: ["--settings", "/app/settings.js"]
    restart: unless-stopped
    volumes:
      - "${NODE_RED_SETTINGS_JS}:/app/settings.js"
      - "nodered-data:/data"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # HTTPS Router Configuration
      - traefik.http.routers.nodered.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.nodered.tls=true
      - traefik.http.routers.nodered.entrypoints=websecure
      - traefik.http.routers.nodered.tls.certresolver=stepca
      # Service Configuration
      - traefik.http.services.nodered.loadbalancer.server.port=1880
    dns_search: proxy
    networks:
      proxy:

networks:
  proxy:
    external: true

volumes:
  nodered-data:
