user:
    password:
        hashed: ENC[AES256_GCM,data:TwL0ZPCdrkHs563iUkWFwKT9gHsPRS4a8nRsBONxAGGNtz/X9CUNw8/OKOKaJpQmkGeq5Jl/Fcdbu4jQhUls75ras7uEtKC4hQ==,iv:DmpNu3OFneVeA/TbEKYsS++gZp18RMzsEL4odOaaOz4=,tag:GgVdRdGNspJG3niSARrhPg==,type:str]
ssh:
    authorized:
        baseship: ENC[AES256_GCM,data:H97DZTxhFN2AuFSap+VWSTWc7Teccoi/dtTYIWCYMiVjhptLorcCo9Xtde2/CjjWGkK7gW6sJjIKaIaSfTq8Y2pgp+F+bQIgpAVTWh67ZHU=,iv:KHwa2PChchHjBxPusiT6juCcEs59iE28HsqMxh0T+XI=,tag:/7QQH7vV1KHLQr9TfgI/kw==,type:str]
        archive: ENC[AES256_GCM,data:adNGhYZ5fUki1ZdDFlOupSm/Us4nJyBx80zRT98abPIE3BOtyx+0++PUdS8OdUMVmp/d3HiRxbB+R5LNMLp03drYzOUpV9D7nvtP96LBo0g=,iv:234Ent07pJOTLi81xXA9BpfNZeMazBDPtsTLFJqWXWc=,tag:yYYgjO6F69VvSgetrDUNcQ==,type:str]
sops:
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZU4vOStBeFp3QzN3b053
            WXFUS3VJcm9FWXdnYVd4M1J6aXZpVEtsVUMwCmI2UVl5UGQ3TzlXWEVsL1lwMkN2
            NlhRZTI0TC9sQUp3QXMvYTFVa0l5aGsKLS0tIHREUE1GYjBEcXFVQ1l0emwzUGlr
            WFQzRE90djQvVGl0bUhVUXhsakxORFUKQWdgo8ReNEFqst6C54zHgGAwdsiwhATX
            SuTGt9t+GFvP5LpIglFT7lY3g3o5p972Hz6THx1Qw3RQEdUuKcmGBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jsh9t5wfjv9extwpmwcwmv9gwdyw3z69lu67es2ttcl7mr58zdlsdpe7ju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSDJTdjd0RGwwZ28zT3FV
            Wi80VmtPLzFlbjVQUURtcTZHTmxkY3JNVTJFCmpEaCtFTG5HTWFqbHUvR2NxRmUw
            ei9HNHlXZ3pOUXVFUnVOWEJ3YzRONnMKLS0tIHFMdGF3YmREVXZSYzBHU0NkdGZK
            eVBNSjBPUFd5V2hSSjhkelZDYUREaXcKyueaLM2akBsRdliUj8BDjb/A8W43nMRi
            hFHyI8S4STfYcyVdjpPPNwP06LR6dqIej/gOvUF1zKQBnTZ6xXUEyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-03T01:26:30Z"
    mac: ENC[AES256_GCM,data:E1d/9ybmllNDyvhjq5jnh0dfwigkZTriXdaCPQbNbucW51d13cY2ro0S71PelnE3lXwe5d8+VGaUwYv/MKM8JADrWzn1Kd4FBa5pI21WU4Rz8Qo/6f0m9nqaXm6IPeLZO1HzJYQz/xjNs6Rxp5DFDz4oth4Ee8IJV9OeU+485Fc=,iv:dmtz2FEmo0rXQq2O6gki7wMUEapdv5OXliBlHLWxABY=,tag:SUyFA1Kct2XYHml9QdV2PA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
