---
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_RETENTION
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    volumes:
      - data:/var/lib/influxdb2
      - config:/etc/influxdb2
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.0.1.14

    labels:
     - traefik.enable=true
     - traefik.http.routers.influxdb.rule=Host(`influxdb.homeworld.lan`)
     - traefik.http.routers.influxdb.tls=true
     - traefik.http.routers.influxdb.entrypoints=websecure
     - traefik.http.routers.influxdb.tls.certresolver=stepca
     - traefik.http.services.influxdb.loadbalancer.server.port=8086
     - traefik.docker.network=proxy
     - com.centurylinklabs.watchtower.enable=true

networks:
  proxy:
    external: true

volumes:
  data:
  config:
