user:
  password:
    hashed: ENC[AES256_GCM,data:Yl3eA45ysoTyCJ9NHsfR4qECV33Hi8+jjXhqmuQw3IfcmFX9GvAjyYJOael/Dt7b+gRFObNCWPpY40WnYqU3I3e5ZX6ocllsyg==,iv:iOb0fUGlErv417ml/dG4hZrmfi4X3lSnrW1MwC+aLI4=,tag:cFAabZUGbS/B6i7lUzbvTw==,type:str]
ssh:
  authorized:
    lstr: ENC[AES256_GCM,data:jCgPta+40g0U33WWVySo0cZl11ER4VbEs1kAvn3DFzLI1WmMllHkvglb7tx1E6QXhlnWmkLTGi56FB1lO6TdGyFBGzVJvaW04dHUP6QXuZU=,iv:lCdC4T8Qu/HJP5Sx4LeQrPUF81bRsdIyZZiqaZO+oUo=,tag:Zfk7JlGCiYj6sj80akDOCg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjblJiMkJMZzdoZWhDZDJM
        a1h6aHAwT1VrU1VRVC83L3I0cG1tYmRhNVJVCi9TbHVjdU1PZ25TeXFTL0JLOEdO
        VTNYcVU0c05TZGtPc3RFQUJyWkUvWWMKLS0tIHc5bkVKZ2pjWC9NaDdVcTBEUUl0
        Z0xPU2oybVI1RlZWMVBNUjRBVVVXVkkKkynrgUV5eri96sZSmM4YZkI9zvukv8vD
        ZSC+rF8BvQYjA/Zqxi4bN3jZxzq9K/PYC2Eorxt/0+qBMBqy3t3aXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydXlVcCs5MjFHc3lLZkd0
        NEY2bGJORzJRdDlQcU9RSDI2V1hPbDNzN0gwCnpHS2VJQkpaYVpVTkhaWlN3VDE1
        WDJBYndhZ0h3Q0RBTUZqRmJyRzVxMWcKLS0tIG81c3hVVVFvUjlaaTlEZVhnSHdY
        UDhXUFVEeGdNRDJIY2tLMWJjTzRYcGsK/DD7KMTcH41RBlzmgq71432aHSYdTfIM
        1KFW0kgBq14094sbNrcwEEWBQYI2P8sr2YYg131HmWOSaPX6Pm3Qrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u20wtv3pkczwhcj4dqjtd5pfgc5fsl8xv5vcae0n77u55nc053rq2h52ve
  lastmodified: "2026-09-12T10:01:26Z"
  mac: ENC[AES256_GCM,data:LWuVnAOXrvk5DGk+8fQqFTnpSweWRrVgzLQdlQv2rytop6jnjOY3zZgNnzWvTjmQ6PL30mmGC+eT+Jllpn5j0ztjc1a85Uyw1t5cOQSLrgXxiFXlTxdRSchSmTnd14ENw/sne7eL35QtfVtp9uPoseH4myfud1gSY+psCLgmxGs=,iv:4+ykIV68UotHcGNZ2v4dMJ3iUHfDB3oQIaCXcuflHtc=,tag:3Ucbq3lExFMDIlugW7yrUw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
