user:
  password:
    hashed: ENC[AES256_GCM,data:TwL0ZPCdrkHs563iUkWFwKT9gHsPRS4a8nRsBONxAGGNtz/X9CUNw8/OKOKaJpQmkGeq5Jl/Fcdbu4jQhUls75ras7uEtKC4hQ==,iv:DmpNu3OFneVeA/TbEKYsS++gZp18RMzsEL4odOaaOz4=,tag:GgVdRdGNspJG3niSARrhPg==,type:str]
ssh:
  authorized:
    lstr: ENC[AES256_GCM,data:jCgPta+40g0U33WWVySo0cZl11ER4VbEs1kAvn3DFzLI1WmMllHkvglb7tx1E6QXhlnWmkLTGi56FB1lO6TdGyFBGzVJvaW04dHUP6QXuZU=,iv:lCdC4T8Qu/HJP5Sx4LeQrPUF81bRsdIyZZiqaZO+oUo=,tag:Zfk7JlGCiYj6sj80akDOCg==,type:str]
sops:
  age:
    - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZU4vOStBeFp3QzN3b053
        WXFUS3VJcm9FWXdnYVd4M1J6aXZpVEtsVUMwCmI2UVl5UGQ3TzlXWEVsL1lwMkN2
        NlhRZTI0TC9sQUp3QXMvYTFVa0l5aGsKLS0tIHREUE1GYjBEcXFVQ1l0emwzUGlr
        WFQzRE90djQvVGl0bUhVUXhsakxORFUKQWdgo8ReNEFqst6C54zHgGAwdsiwhATX
        SuTGt9t+GFvP5LpIglFT7lY3g3o5p972Hz6THx1Qw3RQEdUuKcmGBw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jsh9t5wfjv9extwpmwcwmv9gwdyw3z69lu67es2ttcl7mr58zdlsdpe7ju
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSDJTdjd0RGwwZ28zT3FV
        Wi80VmtPLzFlbjVQUURtcTZHTmxkY3JNVTJFCmpEaCtFTG5HTWFqbHUvR2NxRmUw
        ei9HNHlXZ3pOUXVFUnVOWEJ3YzRONnMKLS0tIHFMdGF3YmREVXZSYzBHU0NkdGZK
        eVBNSjBPUFd5V2hSSjhkelZDYUREaXcKyueaLM2akBsRdliUj8BDjb/A8W43nMRi
        hFHyI8S4STfYcyVdjpPPNwP06LR6dqIej/gOvUF1zKQBnTZ6xXUEyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:47:24Z"
  mac: ENC[AES256_GCM,data:xZgIIeUggT3Lm2cyxpHZpKwARJY9YZKdB9tH88tSBfxnBzaMDyjkQUiMHr48ngSYqz4b8m0JDuqgsTFMLyPQHK/HRGmqjZc9kNBwj1/Yv0EAAZxB+7WV7KjsiImnFLzUhcXtTpBTSVSkjK4BtR1BAbGTEqCva40PaaNR9i+z4tY=,iv:ccK/EYk/5LZA79yrbkypy8jazQWojezMEkdTbeHPJmw=,tag:LRZwilHFVGfWO0Y8wEYcuw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
