user:
  keys:
    ssh:
      public: ENC[AES256_GCM,data:JPa4+s3wX7017orEwusRAOFiuyzCcgiFrwHfArKqrcmPOf30rqee8D7mK6AxKgzdmpxlMp5GFpvKXC9BkSXq76fD3P/P11ifn5lNQHXXWAZir7m0VBJjHqHJksoq1g==,iv:VQCWu+Sny9RQzTUalM2k9OGI3wLwS/OV5+aRt7qMEmk=,tag:AcPQh+j1a8HIvNj7hlXB1Q==,type:str]
      private: ENC[AES256_GCM,data:T8QfCAYOG5ffxCWWBWQVGr4B06KYJxoWVoAeKbf6S+kAcOPIcZZkIsC+wLJqLUmlpFOk/OWx6GEe51fEkyDjdEQSk9tSzXoTx0RBSp1M8zh97EB/LVNf4JSI3+IprhzinEAvAbyoswkXdCouSCT5UeDp/HNMmkPmqnh0YDq+lobJ1bpfBsUgSdHnF7O5azho+3gRvSYbNfJy99BTu6xsbDTHUqcQxeq8Z+c5/7cnV9XTbAzYQ4/BmTVN099OV83vGd3cpj6BTzzzfSFxMuLx7MbaJRGcCqI/vWobe6W5RrIxKa5B4ygZxKgJ3SV55oULUGyQc0yB/xpQwUaJ0PQJIrzHLngGxnOOzlcLfqaOM5N3kfEZtIVR0WquZBNSam9YDQgHmWo+OsU+blMszQO77zCBNa9proIrYz4uZEZCGhYETr0z7FKtX8Mxxdg5agaHMyKbZe58mrW0DvrNVrqZNXAk0Die7qZ6YkQG95/E7JFe1UmLDRtrZoI7tKkFzfTfO3c+wg7v8QpfhH+nlRG2BLilqapW0bT6vkNKPoLc4O8/xEKoICpmdaWnRh8XO1ucFoD6wGZQot24VOG3,iv:/J3BM62uwBu5cXxCNlNfCQP4wal3bqCucD3zyaGvgoE=,tag:Zci5qnWkhy4Jg0RPUA0iIg==,type:str]
      authorized:
        baseship: ENC[AES256_GCM,data:YD35Y3gTCsfbOFqX28SVsLbBxWzdX/yEno0XkQw4fTfYSZ2lVBj6k4jd4AVYWvmF+1IhGuh3EOrh4xh2P49bnMpv6Mu0Ja3QEovqkcBU2x0=,iv:ozdLMKCLF2KddcktGSVlMPQmytATiV4hN4lJZ4jhqpk=,tag:UdnNzcBqtpcv/nbT2xGY9A==,type:str]
sops:
  age:
    - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNmt4NzBaOVlCbDVMcEp1
        WldRWHc5S1BUOGMzNnRpVWVqcjhVRnBjekdrCjNkWUVqOGcrY1l6SVJYZ2thN2xU
        cVN6R0FOZHhmUjBaYzNGdmVKZ0RMZEUKLS0tIGt1ZnIrKy9zOTBpL0ZMYkwrM1ZD
        cEVKYU5Td296cmFibGZUWTZhNHhYQW8KTwQPoK6rdVGz3DTbSGKYcvom8dvKq4bH
        BibaVz2x+Ys1T8W345TFGZ5cW+0xfgKuKq1KAQSowZOpsQaBLgZysA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1x8nn8yvgs2xvr7u7dnqnlrq7h05dvshqsy447c3j2aqek4rk3dqsuprskn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeFZMWUI5Vzd0WnY5dUJn
        eWZ3ZjB6SlZYbmJPYWNOOGJqYnRQZG1nWUVrCmo4OUwvSUNhY1BpSWdiOUpma1NK
        YkFiVmk3UkZpNWpQd1Q1ZmVoa2J5ZFEKLS0tIFR0V0Jsd3RuMkQxZUtwWlpTWWNY
        WjRpUXhobnk3dXdxa01RcjlsNXZNcW8K2yGTDIidEB2oezcXzcbBmu40QmZ83Cyw
        +Of+00zL1CSP4EwCzAZygRiIn6+Qa1VH+p6h1ow46Gch6jsetNFCdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-24T20:26:11Z"
  mac: ENC[AES256_GCM,data:R/6rlM8r5M2YRN8ZZGsqXt7sTgQ6+G6gsIC+iXoswjAM8O7rGtKKyz6ryLSSdDpRLT8JP9IJwxotHGdWyArDmayXjN/eNGRqNn/oAiRDzPkUGjetwKZuRBDAaGp/TPkNFwXwKVXYY4SNTkklsePxllEYTVr1i9B5og5EBHaZ2LQ=,iv:vDONf932SDtOAGIxEiN5QeYBJmvAfVZXZP6sjYT0vBE=,tag:5CJWc4Luawn8WtS2Usvt2w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.9.4
