user:
    password:
        hashed: ENC[AES256_GCM,data:mtKTBkvvoGgSYqMZSnrVyGEx8ptk8FEbGMvNJ0yyYX1gHldOOFaT0AV8TbJV5ZV421JwYqpwaKBhsijpoTk9u3ve7CAwlNlovA==,iv:rCV3iHOTdL4lL1EBEDq2uhXUtopCRCZ0Hkp1duPDwrk=,tag:bml+okc6Oub3N0LGDVYs9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL2I0a0JxRlRWV0lEM3Jj
            N3VpVHhldTBMdC9jMlhIOTFZV0lyMjVmU0drCllDenQ2eHlFTnE5ZHA4dUhzQUdk
            MDZCUzlLcThIZEt3RTFGcXFFREQ1UFUKLS0tIHlFcEhJd1RWM0VoYVc3VUVRbkt3
            MC80dmtPZjd2Y0grMkRnOHJqeExyZjQK2Aqz/hJMCOM0e1v2ZgUdPirNgHUocKkT
            HHdXEw+YW/PvOOh8DujxBUYw+N9GAv289E1nd2gjZckiuXpYHRurlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ustkwg4dht8hydkev74cdvp765aundsggutq66ndm5nmckuddqnqlcrv7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVHQ5b205SS8xM0o2bXpr
            SjNQaVpKd2NUSFNLOVBPbCt2NWs1dkRnSVYwCkJiTG9xV01nTHcweFZQcFE2OVNL
            am5hbkluV0hQbnIwLzl4YkRGYXA2Q00KLS0tIGZoY1ZWd3VBb2ExbFpVSTFuSVlO
            M1JaM3ZHSDArNUtUU0VLUG1WSG5sWmsKMcYtOiC5qJtqhriG3iyb9z6E9CsuRtcV
            eHiexEIOBYY7EIdf+v0cco0jXp8HQAd6BHcBYXFc+Vpupr3Z4kT25w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T03:46:12Z"
    mac: ENC[AES256_GCM,data:6BEVfP4gnBkaV/ho3icCoNqSt5lXdP+O+ilcBFPusV+p+G7A0+uTDcuV5UlQzBDGhGjXp19kRa/xJaQC0ZJFrvOYUKX+1F7Hw+kx/LXM9aslS3LtzogSzWWmRpm8Q11IWlChgJI+kCtcJIf+3ovlKp8VlSoCuuZRBdb2iDua0cI=,iv:AE1gv8fu16H8cnoNSb1Pv5ZgLUtG844zxD/k9E/CtKQ=,tag:wvdM8RFUyUzLRAzrgGYRlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
