---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL="http://${INTERNAL_DOMAIN_NAME}"
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    dns_search: proxy
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # HTTPS Router Configuration
      - traefik.http.routers.open-webui.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.open-webui.tls=true
      - traefik.http.routers.open-webui.entrypoints=websecure
      - traefik.http.routers.open-webui.tls.certresolver=stepca
      # Service Configuration
      - traefik.http.services.open-webui.loadbalancer.server.port=8080
      # Watchtower Configuration
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy:
    external: true

volumes:
  open-webui:
