user:
  password:
    hashed: ENC[AES256_GCM,data:7P9vC5bZcI3wsHbAcTdD48aoz8FiRhhf6NnzUxSLb40WW/wrzb4yNpU00ZEx5MgyUvykWh19dOzM8UTvBJPzaq4ZwgbIUFlPFw==,iv:zFHTtsR5AozIjOG3GAi98ZUQ0htsmKFwKER2FJ+g5Gs=,tag:ZrC3uYTmu+W/fTn7hGP4vQ==,type:str]
ssh:
  authorized:
    lstr: ENC[AES256_GCM,data:+8ZZV7i0Cbm/T2EbqwD0VWBLX412t9bz6iWp1yawnfKoXVl8xAIeV44mNl+grrpB2/q3v3s/IqeVV9ZCJdTZUgo0TK29ITr1ZbywhkWE6d0=,iv:CyHMEd+XSUsMfnmvLUiUrHJmBgenmwO+LDLZXDnk73I=,tag:AkZ0IcUv/NUF+eJIiT0KJg==,type:str]
    eulr: ENC[AES256_GCM,data:bxo+Dy8XIrwjr67Eq8m/zqmyrkhCk/bIXeCgNR8wyBhBE36LT6rW1iiXeiuDoGuIzzY5+x9F+vesLJVpDN1a/J4VWuDzzu45GgeksOG3TzA=,iv:ZS5lcik6gMolCbRwbA0XgaFNQqmuCU1LrNuLWfRVrvc=,tag:dzNCC07dvB2Q16SjN1aesQ==,type:str]
sops:
  age:
    - recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSnlvNWl2Z1d6Y2xSMVEy
        dVdFRi84bFJXTHRlM08raUw4NXB5S283V2dNCjR4TEZESW5mOWwzOEZsKzd2cUZk
        b2pjUnkyWWJiTlRSeUZPL0ZTcHhhUEUKLS0tIHhBRys1cTRjZnZxS0J5T2taL2tU
        eU1hdEVWTWY5YktHTlNXczRoUzloUkEKKfpMzR1zJqpqqxUGYW9X8Nn8DRAqI9zC
        aGDTfTNKeOqPdYkqHs+bUpclrUE68kkgfzQA5vQay6tnF5tSj1h2UQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1p0el9phnfxnjnaa9mgqtru4ke30vcae7vlzffmre2czf4r5w54rqwm8f0z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaEVCdC9uUmxaYVp5dU9K
        anQ1RitaVG9PSkRZVFFaSWNSV01XZmFhSm1JCnE0TTVRWUkwTVZaUmxmT3lrdDhJ
        aTZQclcrUU94UUZOZ0ZCeVFTZ1QvR0EKLS0tIFhSbjVXYVVINGkxL25tb2xVd0RN
        dDNpSlFrMWIxM2NZZUFybGFiQ2hELzQKDQEViMt7sEcjebOqNK1+jfSe7SDxofXT
        jV6Lflxh6vVZyZbIQDHc5+tdXEW+QzJejtoZX8Rgky1PQl9lPfcFnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-21T23:06:08Z"
  mac: ENC[AES256_GCM,data:PfIbsUc9tAL2agASQgoUsW1gCX2SeoNdVQe2B7ZwcH3cmUkrqBGR4QtAP/vS6UFwEwrPVIxalqNdoTW4IJyaCI9JvEdDhlImDDz2x4L6a0gFGD5j1OM1o3YnR2IljzIDxW0KTLOnYWdEZO5MxSFGjps3YgzF5kKj80LnhsiA1v4=,iv:QfFdvzIKon85x9AADLcdnHU/0Zc0YpMDHQ/PgRlgDe4=,tag:9qfMQWMbCU7U+5rdHUvqRg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
