---
services:
  cinny:
    container_name: cinny-web
    image: ghcr.io/cinnyapp/cinny:latest
    labels:
      - traefik.http.routers.cinny.rule=Host(`cinny.homeworld.lan`)
      - traefik.http.services.cinny.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.0.1.9

networks:
  proxy:
    external: true
