user:
  password:
    hashed: ENC[AES256_GCM,data:OVIYZon7oeG31XnNC6151sPNVzi8D/rvKFtfe24cKloKzpwb0up7219S22qni06D+ofjb6FZbppU/YR3tarz2bwb8ThgjSEfqZyhiY9b3sRsQq1Y0aAePnDZrAiNBw1BxKQHWUmblJgYJQ==,iv:AYjg4UjNKyLf5+ZLBRhJ1lruX3mAbO2wsRDFOHGUJQk=,tag:mGK0mGp0IuJ8vic6k52Dvw==,type:str]
root:
  password:
    hashed: ENC[AES256_GCM,data:mJaB7KFt9NCeZJB410a0Fffikfp4k9R+cZHqNFXw+X1X8TR7aqaUpIzfV7NUuAL4+XiB8wFqW+653RR9SonNgJN9j3TuXG68B8bRzaWTpyyuTv+GjMrBYRRbU4ZB78jxR4zQaKMC275Hig==,iv:m+CmCBPWGJyhv4b45d/iUKJ4FJvFwGfNfW2ogZo++/k=,tag:Rdbj3axmS24OEAQEarDFTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbFJpNEgrMDdpNlhnRjlL
        ZXZXdlRXMWFyRXM4aVI0N2tWWjN0eEh0SW1FCnRaZTlxUUwwNmIxcEZweVdjNzJx
        VEl5alhGdVJxVkJzV3gvTW5zQ2Y0UUEKLS0tIEdkVkJDVks2aDMyVVB2MVdINnJk
        UFVmR0xxRGlqMWxRb1pIUm5CdEtkV2sKMPA9YhcgSkJxE/1vWZHhusmSwyRxMADn
        bruIxhrj4pOIrmiWAKu8EArjM0V1Ndtwc/N7KORaLOfAcLKyOnyTmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140q4kedpqnf3jnpkhr6t4uq5ptp39mgvtn9pavdx3rj4vq5weasqnutaxp
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbExZWnNpeG9kdGoyYXhp
        c3k5Mi9TQ0JSd3g4cVNIeUp2UE53ZVVWbG1ZCmZ4MlRhOThkRjlaTnVicXdwdk03
        NEhScGFLOUJmVVM3T0dOOW1QRWpndlkKLS0tIHNsYXNTUGNvTWcwZ2JCVjBKWHZl
        Vk5VT1BUejZGNElUK2x5SnpUenBrVFkKsJLPdpR+NzhgpB1CVJYsK1xGLTS2yI/y
        vM2L4kGyT1B46XssQgeD1NfgReC1SUq1amXMMYW65+AcYHbRXml9Og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nnxphkwuzdckpm6vdahzumpnkwjawjau49mg35r3jffzahqudqmqvy4pgd
  lastmodified: "2026-10-06T22:35:22Z"
  mac: ENC[AES256_GCM,data:8ejZDZHQ+bX+wtDUrjhqkCmOb2HMx9LKn+ZyOpRWVfXLrA38r0TK3kNtm6UUpP2y7hT6GWGnUgoQaVI4CaR47sBSQdYAMNSMOh38WDY0/PNebM5JV6FzSN9vBICy2bDJuoHQpYfMNYBPD+g5ogDMWsXNMAdA30I0CP6LbIlcOaE=,iv:NyEcBeXsMWlUPT2SNuT1Alo1JQFWO3JDYCRcJv9z2wM=,tag:S7C9ozFWePaAX/j10n4P2g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
