---
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Lisbon
      - NTFY_BASE_URL=https://${INTERNAL_DOMAIN_NAME}
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ENABLE_LOGIN=true
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
    volumes:
      - data:/var/lib/ntfy
    restart: no
    dns_search: proxy
    networks:
      proxy:
    labels:
     - traefik.enable=true
     - traefik.docker.network=proxy
      # HTTPS Router Configuration
     - traefik.http.routers.ntfy.rule=Host(`${INTERNAL_DOMAIN_NAME}`)
     - traefik.http.routers.ntfy.tls=true
     - traefik.http.routers.ntfy.entrypoints=websecure
     - traefik.http.routers.ntfy.tls.certresolver=stepca
      # Service Configuration
     - traefik.http.services.ntfy.loadbalancer.server.port=80

networks:
  proxy:
    external: true

volumes:
  data:
