---
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Lisbon
      - NTFY_BASE_URL=https://ntfy.homeworld.lan
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ENABLE_LOGIN=true
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
    volumes:
      - data:/var/lib/ntfy
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.0.1.12
    labels:
     - traefik.enable=true
     - traefik.http.routers.ntfy.rule=Host(`ntfy.homeworld.lan`)
     - traefik.http.routers.ntfy.tls=true
     - traefik.http.routers.ntfy.entrypoints=websecure
     - traefik.http.routers.ntfy.tls.certresolver=stepca
     - traefik.http.services.ntfy.loadbalancer.server.port=80
     - traefik.docker.network=proxy

networks:
  proxy:
    external: true

volumes:
  data:
