---
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      proxy:
        ipv4_address: 10.0.1.3
    labels:
      - traefik.http.routers.adguard.rule=Host(`adguard.homeworld.lan`)
      - traefik.http.services.adguard.loadbalancer.server.port=80
      - traefik.docker.network=proxy
    ports:
      # DNS
      - "53:53/tcp"
      - "53:53/udp"
      # DHCP
      - "67:67/udp"
      # - "68:68/udp"
      # DNS-over-TLS
      - "853:853/tcp"
      # Additional DNS ports
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      # DNS-over-QUIC
      - "5443:5443/tcp"
      - "5443:5443/udp"

volumes:
  adguard_work:
  adguard_conf:

networks:
  proxy:
    external: true

