---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST
      - PASSWORD_HASH
      - LANG=en
      - UI_TRAFFIC_STATS=true
      - WG_DEFAULT_DNS=${DOCKER_DNS_IP}
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - UI_CHART_TYPE=1
    volumes:
      - wg-easy-config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    labels:
     - traefik.enable=true
     - traefik.http.routers.wg.rule=Host(`wg.homeworld.lan`)
     - traefik.http.routers.wg.tls=true
     - traefik.http.routers.wg.entrypoints=websecure
     - traefik.http.routers.wg.tls.certresolver=stepca
     - traefik.http.services.wg.loadbalancer.server.port=51821
     - traefik.docker.network=proxy

    networks:
      wg-easy:
      proxy:

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: dns.adguard.container
    restart: unless-stopped
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
      proxy:
        ipv4_address: "${DOCKER_DNS_IP}"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # HTTP Router Configuration
      - traefik.http.routers.adguard.rule=Host(`adguard.homeworld.lan`)
      - traefik.http.routers.adguard.entrypoints=web
      - traefik.http.routers.adguard.service=adguard-service
      # Shared Service Configuration
      - traefik.http.services.adguard-service.loadbalancer.server.port=80
    ports:
      # DNS
      - "53:53/tcp"
      - "53:53/udp"
      # DHCP
      - "67:67/udp"
      # - "68:68/udp"
      # DNS-over-TLS
      - "853:853/tcp"
      # Additional DNS ports
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      # DNS-over-QUIC
      - "5443:5443/tcp"
      - "5443:5443/udp"

volumes:
  adguard_work:
  adguard_conf:
  wg-easy-config:

networks:
  wg-easy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.8.1.0/24"
  proxy:
    external: true

